# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbdbbce2da5c4c376e2620f005cebcf042c5e1b7dbb86901da873fea18ce39cafc88456b717d41aa77a95a5f75e6b800e47058f5e63109e06d8b7e89f5bdf0f6

test:
  secret_key_base: deb9938d7374a60ef71b3880ddab9eeb072bbfae8b4d1d3bc8d4cf3b2a17de4c23a9942c1901e62922ffefcde67100956522b0e48c84ab25d737b292bd8dcd81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
